- name: add apt key 
  apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    state: present
  tags: apt-key

- name: add repo
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    mode: 0644
    owner: root
    group: root

- name: update repo
  shell: sed -i 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Install the NVIDIA Container Toolkit package
  shell: apt update -y && apt install -y nvidia-container-toolkit
  
- name: Configuring Docker
  shell: nvidia-ctk runtime configure --runtime=docker

- name: Modify daemon.json
  tags: 
  - instconf
  notify:
  - restart docker
  template:
    src: daemon.json
    dest: "/etc/docker/daemon.json"
    mode: 0744
    owner: root
    group: root

- name: copy grub 
  copy:
    src: grub 
    dest: /etc/default/grub
    mode: 0644

- name: reboot node
  shell: update-grub && reboot
